In [1]:
#문제 1

In [2]:
import numpy as np
array = np.array([[1,2,3],[3,4,5],[5,6,7],[10,20,30]])

print(array[2:3,0:1])
print()
print(array[3,:])
print()
print(array[2:,:])
print()
print(array[1:3,::2])
print()
print(array[2:3,:])

[[5]]

[10 20 30]

[[ 5  6  7]
 [10 20 30]]

[[3 5]
 [5 7]]

[[5 6 7]]


In [3]:
#문제 2

In [4]:
an_array = np.array([[11,12],[21,22],[31,32]])
an_array[(an_array > 20) & (an_array < 30)]

array([21, 22])

In [5]:
#문제 3

In [6]:
a = np.arange(15)
array = a.reshape(3,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
#문제 4

In [8]:
array[array % 3 == 0]+=50
array

array([[50,  1,  2, 53,  4],
       [ 5, 56,  7,  8, 59],
       [10, 11, 62, 13, 14]])