In [1]:
#문제 1

In [2]:
import numpy as np
array = np.arange(24).reshape(3,4,2)
array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [3]:
#문제 1-1

In [4]:
s0 = array.sum(axis = 0)
s1 = array.sum(axis = 2)
s2 = array.sum(axis = 1)
print(s0)
print()
print(s1)
print()
print(s2)

[[24 27]
 [30 33]
 [36 39]
 [42 45]]

[[ 1  5  9 13]
 [17 21 25 29]
 [33 37 41 45]]

[[12 16]
 [44 48]
 [76 80]]


In [5]:
#문제 1-2

In [6]:
s0 = array.mean(axis = 2)
s1 = array.mean(axis = 1)
s2 = array.mean(axis = 0)
print(s0)
print()
print(s1)
print()
print(s2)

[[ 0.5  2.5  4.5  6.5]
 [ 8.5 10.5 12.5 14.5]
 [16.5 18.5 20.5 22.5]]

[[ 3.  4.]
 [11. 12.]
 [19. 20.]]

[[ 8.  9.]
 [10. 11.]
 [12. 13.]
 [14. 15.]]
